# Generated by Django 5.0.6 on 2026-04-25 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'db_table': 'inventory_stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('return', 'Return'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('opening', 'Opening Stock')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive = added to stock; negative = removed from stock.', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Reference: sale ID, PO number, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
