# Generated by Django 5.0.6 on 2026-05-15 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productbatch'),
        ('products', '0005_product_expiry_alert_days'),
        ('tenants', '0007_inbound_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbound Transaction',
                'verbose_name_plural': 'Inbound Transactions',
                'db_table': 'inventory_inbound_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundTransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Inbound Transaction Item',
                'verbose_name_plural': 'Inbound Transaction Items',
                'db_table': 'inventory_inbound_transaction_items',
            },
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_product_81868e_idx',
            old_name='inv_batch_prod_shop_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_shop_id_3df517_idx',
            old_name='inv_batch_shop_exp_idx',
        ),
        migrations.AddField(
            model_name='inboundtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundtransaction',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transactions', to='tenants.shop'),
        ),
        migrations.AddField(
            model_name='inboundtransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transactions', to='tenants.business'),
        ),
        migrations.AddField(
            model_name='inboundtransactionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='inboundtransactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inboundtransaction'),
        ),
        migrations.AddIndex(
            model_name='inboundtransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='inventory_i_tenant__e4311c_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundtransaction',
            index=models.Index(fields=['shop', 'created_at'], name='inventory_i_shop_id_15e453_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundtransaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference'), name='unique_inbound_ref_per_tenant'),
        ),
    ]
