# Generated by Django 5.0.6 on 2026-04-25 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('sale', 'Sale'), ('stock', 'Stock Alert'), ('subscription', 'Subscription'), ('system', 'System')], db_index=True, default='info', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra structured data for the notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_6ae36f_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_870947_idx')],
            },
        ),
    ]
