# Generated by Django 5.0.6 on 2026-05-12 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken_notificationdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notifications_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('both', 'Both')], default='push', max_length=10)),
                ('title_en', models.CharField(max_length=255)),
                ('body_en', models.TextField()),
                ('title_ar', models.CharField(max_length=255)),
                ('body_ar', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notifications_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_user_id_6ca9e6_idx',
            old_name='notif_dt_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_recipie_e6f087_idx',
            old_name='notif_del_recipient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_channel_765447_idx',
            old_name='notif_del_channel_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_status_938482_idx',
            old_name='notif_del_status_created_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('sale', 'Sale'), ('stock', 'Stock Alert'), ('subscription', 'Subscription'), ('security', 'Security'), ('system', 'System')], db_index=True, default='info', max_length=20),
        ),
    ]
