# Generated by Django 5.0.6 on 2026-04-25 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('max_shops', models.PositiveIntegerField(default=1, help_text='Max number of shops.')),
                ('max_products', models.PositiveIntegerField(default=100, help_text='Max number of products.')),
                ('max_users', models.PositiveIntegerField(default=3, help_text='Max number of staff users.')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription duration in days.')),
                ('features', models.JSONField(default=dict, help_text="Feature flags, e.g. {'reporting': true, 'api_access': false}")),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False, help_text='Marks this as a free/trial plan.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'subscriptions_plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
