# Generated by Django 5.0.6 on 2026-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_shops',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
