# Generated by Django 5.0.6 on 2026-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_duration_days_alter_plan_features_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date', 'is_active'], name='subs_end_date_active_idx'),
        ),
    ]
