# Generated by Django 5.0.6 on 2026-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_assign_cashiers_default_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_index=True, default='en', max_length=5),
        ),
    ]
