# Generated by Django 5.0.6 on 2026-05-01 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_subs_end_date_active_idx'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_at'], name='biz_created_at_idx'),
        ),
    ]
