# Generated by Django 5.0.6 on 2026-05-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_shop_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='tenants_sho_busines_d1ce58_idx',
            old_name='tenants_sho_busines_is_main_idx',
        ),
    ]
