# Generated by Django 5.0.6 on 2026-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_business_currency_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(blank=True, default='SDG', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Khartoum', max_length=60),
        ),
    ]
