# Generated by Django 5.0.6 on 2026-04-25 14:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit - unique per tenant.', max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode (EAN, UPC, QR, etc.)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Purchase/cost price.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit', models.CharField(choices=[('pcs', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('m', 'Meter'), ('box', 'Box'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('other', 'Other')], default='pcs', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('track_inventory', models.BooleanField(default=True, help_text='Whether inventory should be tracked for this product.')),
                ('min_stock_level', models.PositiveIntegerField(default=0, help_text='Alert when stock falls below this level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'products_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
