# Generated by Django 5.0.6 on 2026-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_bankak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bankak', 'Bankak'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_wallet', 'Mobile Wallet'), ('loyalty_points', 'Loyalty Points'), ('split', 'Split Payment'), ('credit', 'Credit')], db_index=True, default='cash', max_length=30),
        ),
    ]
