# Generated by Django 5.0.6 on 2026-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_dashboard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
